# -*- coding: utf-8 -*-
"""Week 8 迴圈20

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gQb718mUbYYSTX5JBgXrRHu3YcGpVbY5
"""

i = 2
while i <= 20:
    print(i)
    i += 2