# -*- coding: utf-8 -*-
"""Week 8 隨堂練習：承接上題，介於 x 到 y 之間的奇數有幾個（包含 x 與 y 假如它們是奇數）

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gQb718mUbYYSTX5JBgXrRHu3YcGpVbY5
"""

x = int(input("請輸入起始的正整數:"))
y = int(input("請輸入終止的正整數"))
i = x
while i <= y:
    if i % 2 == 1:
        print(i)
    i += 1