# -*- coding: utf-8 -*-
"""Week 8 迴圈10 done

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gQb718mUbYYSTX5JBgXrRHu3YcGpVbY5
"""

i = 1
while i <= 10:
    print(i)
    i += 1
print("Done")