# -*- coding: utf-8 -*-
"""Week2加分作業

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18jpZEIs6gdWQ4hvTmxAxf1WKAZ8iTsrA
"""

print("Hello World")

import this