# -*- coding: utf-8 -*-
"""Week 4 球員 BMI 與過重判斷

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJWXp-PVSet9NcchzFicJEErHr64d5Lb
"""

#球員 BMI 與過重判斷
name=input("請輸入球員姓名?")
height=int(input("請輸入球員身高（cm）?"))
weight=int(input("請輸入球員體重（kg）?"))
BMI=weight/(height/100)**2
print("{}的BMI為:{:.2f}".format(name,BMI))

print("{}是否過重:{}".format(name,BMI>30))