# -*- coding: utf-8 -*-
"""Week 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NxBm1XhTaGjoSi55yZJ7uTgU4lw90Ilz
"""

#溫度轉換(攝氏轉華氏)
temperature=int(input("Please enter the current tempc:"))
current_tempf=current_tempc*9/5+32
print(current_tempf)

#溫度轉換(華氏轉攝氏)
temperature=int(input("Please enter the current tempf:"))
current_tempc=(current_tempf-32)*5/9
print(current_tempc)

#計算俠客歐尼爾巔峰時期的BMI身體質量指數
shaq_height = 216
shaq_weight = 147
BMI=shaq_weight/(shaq_height/100)**2
print(BMI)

#What did Ross say?
ross_said=("""Let's put aside the fact that you "accidentally" pick up my grandmother's ring.""")
print(ross_said)

#讓使用者輸入城市名稱與天氣
city=input("請輸入城市:")
weather=input("請輸入天氣:")
print("我在{}，天氣{}".format(city,weather))

#球員 BMI 與過重判斷
name=input("請輸入球員姓名?")
height=int(input("請輸入球員身高（cm）?"))
weight=int(input("請輸入球員體重（kg）?"))
BMI=weight/(height/100)**2
print("{}的BMI為:{:.2f}".format(name,BMI))

print("{}是否過重:{}".format(name,BMI>30))