# -*- coding: utf-8 -*-
"""Week 4 溫度轉換(攝氏轉華氏)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJWXp-PVSet9NcchzFicJEErHr64d5Lb
"""

#溫度轉換(攝氏轉華氏)
current_tempc=int(input("Please enter the current tempc:"))
current_tempf=current_tempc*9/5+32
print(current_tempf)