# -*- coding: utf-8 -*-
"""Week 4 What did Ross say?

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJWXp-PVSet9NcchzFicJEErHr64d5Lb
"""

#What did Ross say?
ross_said=("""Let's put aside the fact that you "accidentally" pick up my grandmother's ring.""")
print(ross_said)