# -*- coding: utf-8 -*-
"""Week 4 俠客歐尼爾BMI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJWXp-PVSet9NcchzFicJEErHr64d5Lb
"""

#計算俠客歐尼爾巔峰時期的BMI身體質量指數
shaq_height = 216
shaq_weight = 147
BMI=shaq_weight/(shaq_height/100)**2
print(BMI)