# -*- coding: utf-8 -*-
"""Week 4 溫度轉換(華氏轉攝氏)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJWXp-PVSet9NcchzFicJEErHr64d5Lb
"""

#溫度轉換(華氏轉攝氏)
current_tempf=int(input("Please enter the current tempf:"))
current_tempc=(current_tempf-32)*5/9
print(current_tempc)