# -*- coding: utf-8 -*-
"""Week 4 What did Ross say?

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJWXp-PVSet9NcchzFicJEErHr64d5Lb
"""

#讓使用者輸入城市名稱與天氣
city=input("請輸入城市:")
weather=input("請輸入天氣:")
print("我在{}，天氣{}".format(city,weather))