# -*- coding: utf-8 -*-
"""Week 12 隨堂練習

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nR0DNu8jIjIKcuRcI9-4qPhtZl1J2aYu
"""

avengers = ["The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"]
for  av,movie in enumerate(avengers):
    print("第{}部上映的復仇者聯盟電影:{}".format(av+1, movie))

