# -*- coding: utf-8 -*-
"""Week 6 判斷奇數偶數

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FIeTkUIrKGQOScX9KVQsYjai7N3iLDeB
"""

#隨堂練習：判斷奇數偶數
number = int(input("請輸入一個正整數："))
if (number % 2) == 0:
   print("{} 是偶數！".format(number))
elif(number % 2) == 1:
   print("{} 是奇數!".format(number))