# -*- coding: utf-8 -*-
"""Week 6 月薪超過 4 萬或存款超過 50 萬就發信用卡

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cfciI3m13r0nUGNOHerjrYh0sUlm1gSG
"""

#隨堂練習：月薪超過 4 萬或存款超過 50 萬就發信用卡
monthly_income = int(input("請輸入月薪："))
saving_account = int(input("請輸入存款："))
if monthly_income > 40000:
    print("可以發信用卡~")
elif saving_account > 500000:
    print("可以發信用卡~")

else: print("不可以發信用卡~")