# -*- coding: utf-8 -*-
"""Week 6  依身分證字號尾數決定星期幾可以購買口罩

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m8iL_JyTePOfWOOMdIJtsvOj0xRUaIYK
"""

#隨堂練習：依身分證字號尾數決定星期幾可以購買口罩
#奇數：星期一三五日領
#偶數：星期二四六日領
id_last_number = int(input("請輸入身分證尾數號:"))
if (id_last_number % 2) == 0:
  print("星期二四六日可領口罩")
elif (id_last_number % 2) == 1:
  print("星期一三五日可領口罩")