# -*- coding: utf-8 -*-
"""Week 6 Fizz-Buzz

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nj_gCRpnliSQ3OeAf5pWbHSV2p3W_JWZ
"""

#Fizz-Buzz:
#以 input() 函數請使用者輸入一個正整數
#如果是 3 的倍數印出 "Fizz"
#如果是 5 的倍數印出 "Buzz"
#如果是 15 的倍數印出 "Fizz Buzz"
#其他情況印出該正整數即可
number = int(input("請輸入一個正整數："))
if(number % 15)== 0:
  print("Fizz Buzz")
elif(number % 3) == 0:
  print("Fizz")
elif(number % 5) == 0:
  print("Buzz")
else:print(number)