# -*- coding: utf-8 -*-
"""Week 6 判斷 BMI 的類別標籤

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mH70qu5KSmK8fCNci9UelO6Q3b6Z-gCe
"""

#隨堂練習：判斷 BMI 的類別標籤
height=int(input("請輸入身高（cm）?"))
weight=int(input("請輸入體重（kg）?"))
BMI=weight/(height/100)**2
if(BMI < 18.5):
  print("身高 {} 公分、體重 {} 公斤，是 Underweight".format(height, weight))
elif(18.5 <= BMI < 25):
  print("身高 {} 公分、體重 {} 公斤，是 Normal weight ".format(height, weight))
elif(25 <= BMI <30 ):
  print("身高 {} 公分、體重 {} 公斤，是 Overweight ".format(height, weight))
else: print("身高 {} 公分、體重 {} 公斤，是 Obese ".format(height, weight))