# -*- coding: utf-8 -*-
"""Week 6 隨堂練習

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Eq2jXlOH27voQsYkfSLjZ-xk1COEwNH
"""

id_last_digit = input("請輸入您身分證字號的尾數：")
id_last_digit = int(id_last_digit)
print(id_last_digit)
print(type(id_last_digit))
modulo = id_last_digit % 2
ans = modulo == 1
print(ans)