# -*- coding: utf-8 -*-
"""Week 13 隨堂練習(字串裡面 'bob' 出現的次數

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9aejTPM7y2xrGct4pM3gom8BQOqotd1
"""

# 'azcbobobegghakl'
test_str = 'azcbobobegghak'
n_char = len(test_str)
n_bobs = 0
for i in range(n_char - 2):
    #print(test_str[i:i+3])
    if test_str[i:i+3] == 'bob':
        n_bobs += 1
print(n_bobs)

