# -*- coding: utf-8 -*-
"""Week 13 隨堂練習(a,e,i,o,u個數)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9aejTPM7y2xrGct4pM3gom8BQOqotd1
"""

#'azcbobobegghakl'
n_vowels = 0
for i in 'azcbobobegghakl':
    if i in ['a','e','i','o','u']:
      #print(i)
      n_vowels += 1
print(n_vowels)

