# -*- coding: utf-8 -*-
"""Week 13 隨堂練習(判斷輸入是否為質數)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9aejTPM7y2xrGct4pM3gom8BQOqotd1
"""

def is_prime(x):
    """
    Returns True if x is a prime, or returns False
    """
    divisors = []
    for i in range(1, x+1):
        if x % i == 0:
            divisors.append(i)
    n_divisors = len(divisors)
    if n_divisors == 2:
        return True
    else:
        return False
is_prime(1)

