# -*- coding: utf-8 -*-
"""Week 13 隨堂練習(計算 BMI 身體質量指數)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9aejTPM7y2xrGct4pM3gom8BQOqotd1
"""

def get_bmi(height, weight):
    """
    Calculate BMI based on height and weight
    """
    height = height / 100
    bmi = weight / height**2
    return bmi
get_bmi(198, 129)

