# -*- coding: utf-8 -*-
"""Week 13 隨堂練習(計算 range(1, 101) 的樣本標準差)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9aejTPM7y2xrGct4pM3gom8BQOqotd1
"""

#計算 range(1, 101) 的樣本標準差
from statistics import stdev

stdev(range(1, 101))

