# -*- coding: utf-8 -*-
"""Week 13 隨堂練習(將攝氏氣溫轉換為華氏氣溫)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E9aejTPM7y2xrGct4pM3gom8BQOqotd1
"""

def get_fahrenheit(x):
    """
    Transform a Celsius degree into  Farenheit scale
    """
    fah = x * 9/5 + 32
    return fah
get_fahrenheit(32)

