# -*- coding: utf-8 -*-
"""Week 10 隨堂練習2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rPXnVEMVMW12PheuRb0j6HQ65_w5zRI9
"""

#參考 cast 與 https://www.imdb.com/title/tt4154796 將第一集復仇者聯盟的六位英雄選出來
cast = ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson', 'Jeremy Renner', 'Don Cheadle', 'Paul Rudd', 'Benedict Cumberbatch', 'Chadwick Boseman', 'Brie Larson', 'Tom Holland', 'Karen Gillan', 'Zoe Saldana', 'Evangeline Lilly']
print(cast[:6])