# -*- coding: utf-8 -*-
"""Week 10 隨堂練習1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rPXnVEMVMW12PheuRb0j6HQ65_w5zRI9
"""

#參考 cast 與 https://www.imdb.com/title/tt4154796 將飾演奇異博士（Doctor Strange）的演員用 indexing 方式選出來
cast = ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson', 'Jeremy Renner', 'Don Cheadle', 'Paul Rudd', 'Benedict Cumberbatch', 'Chadwick Boseman', 'Brie Larson', 'Tom Holland', 'Karen Gillan', 'Zoe Saldana', 'Evangeline Lilly']
# 從開頭數
print(cast[8])
#從末端數
print(cast[-7])